#define TEAST 0
#define TWEST 1
#define TGUERRILA 2
#define TCIVILIAN 3
#define TSIDEUNKNOWN 4
#define TENEMY 5
#define TFRIENDLY 6
#define TLOGIC 7

#define TRUE 1
#define FALSE 0

#define VSOFT 0
#define VARMOR 1
#define VAIR 2

// TYPE SCOPE
#define PRIVATE 0
#define PROTECTED 1
#define PUBLIC 2

#define CANSEERADAR 1
#define CANSEEEYE 2
#define CANSEEOPTICS 4
#define CANSEEEAR 8
#define CANSEECOMPASS 16
#define CANSEERADARC CANSEERADAR+CANSEECOMPASS
#define CANSEEALL 31

#define READANDWRITE 0 //! ANY MODIFICATIONS ENABLED
#define READANDCREATE 1 //! ONLY ADDING NEW CLASS MEMBERS IS ALLOWED
#define READONLY 2 //! NO MODIFICATIONS ENABLED
#define READONLYVERIFIED 3 //! NO MODIFICATIONS ENABLED, CRC TEST APPLIED

#define LOCKNO		0
#define LOCKCADET	1
#define LOCKYES		2

#define WEAPONNOSLOT		0	// DUMMY WEAPONS
#define WEAPONSLOTPRIMARY	1	// PRIMARY WEAPONS
#define WEAPONSLOTSECONDARY	4	// SECONDARY WEAPONS
#define WEAPONSLOTHANDGUN	2	// HANDGUN
#define WEAPONSLOTHANDGUNITEM	16 // HANDGUN MAGAZINES
#define WEAPONSLOTITEM		256	// ITEMS
#define WEAPONSLOTBINOCULAR	4096	// BINOCULAR
#define WEAPONHARDMOUNTED	65536

#define SPEED_STATIC 1E10

#define NEVER_DESTROY 1000	// FOR MP - DESTROYING DEAD BODIES

#define TRACERECOLOR 0.2,0.8,0.1
#define TRACERWCOLOR 0.8,0.5,0.1
#define TRACERGCOLOR 0.7,0.7,0.5
#define TRACERNCOLOR 0,0,0 // USED FOR SNIPER / SILENCED RIFLES

#define TRACERECOLORF {TRACERECOLOR,0.040}
#define TRACERWCOLORF {TRACERWCOLOR,0.040}
#define TRACERGCOLORF {TRACERGCOLOR,0.040}
#define TRACERNCOLORF {TRACERNCOLOR,0.005}

#define TRACERSECOLORF {TRACERECOLOR,0.25}
#define TRACERSWCOLORF {TRACERWCOLOR,0.25}

#define TRACER_W_ALWAYS TRACERCOLOR[]=TRACERWCOLORF;TRACERCOLORR[]=TRACERWCOLORF
#define TRACER_W_OPTIONAL TRACERCOLOR[]=TRACERWCOLORF;TRACERCOLORR[]=TRACERNCOLORF
#define TRACER_W_STRONG TRACERCOLOR[]=TRACERSWCOLORF;TRACERCOLORR[]=TRACERSWCOLORF

#define TRACER_E_ALWAYS TRACERCOLOR[]=TRACERECOLORF;TRACERCOLORR[]=TRACERECOLORF
#define TRACER_E_OPTIONAL TRACERCOLOR[]=TRACERECOLORF;TRACERCOLORR[]=TRACERNCOLORF
#define TRACER_E_STRONG TRACERCOLOR[]=TRACERSECOLORF;TRACERCOLORR[]=TRACERSECOLORF

#define TRACER_G_ALWAYS TRACERCOLOR[]=TRACERGCOLORF;TRACERCOLORR[]=TRACERGCOLORF
#define TRACER_G_OPTIONAL TRACERCOLOR[]=TRACERGCOLORF;TRACERCOLORR[]=TRACERNCOLORF

#define TRACER_N_ALWAYS TRACERCOLOR[]=TRACERNCOLORF;TRACERCOLORR[]=TRACERNCOLORF

#define LOCKNO		0
#define LOCKCADET	1
#define LOCKYES		2

class VehicleCompartments
{
  Compartment1 = 1;
  Compartment2 = 2;
  Compartment3 = 4;
  Compartment4 = 8;
};

#define CM_NONE        0
#define CM_LOCK_VISUAL 1
#define CM_LOCK_IR     2
#define CM_LOCK_LASER  4
#define CM_LOCK_RADAR  8
#define CM_MISSILE     16
