  class I_Soldier_SL_F;
  class I_medic_F;
  class I_Soldier_F;
  class UK3CB_ION_I_Desert_Offroad_Comms;
  class RHS_MELB_AH6M;
  class RHS_MELB_MH6M;
  class UK3CB_CW_US_B_LATE_UH60M;
  class RHS_UH60M_MEV2;
  class UK3CB_ION_B_Desert_Bell412_Utility;
  class UK3CB_ION_B_Desert_Bell412_Armed;
  class UK3CB_ION_B_Desert_Bell412_Armed_AT;
  class RAF_Chinook_Transport;
  class UK3CB_ION_I_Urban_SUV_Armed;
  class UK3CB_ION_I_Urban_SUV_Armoured;
  class UK3CB_ION_I_Urban_Pickup;
  class UK3CB_ION_B_Winter_Transit_Service;
  class UK3CB_ION_B_Winter_Transit_Transport;
  class UK3CB_ION_B_Winter_Transit_Cargo;
  class B_T_Truck_01_covered_F;
  class B_T_Truck_01_Repair_F;
  class B_T_Truck_01_mover_F;
  class B_T_Truck_01_medical_F;
  class B_T_Truck_01_fuel_F;
  class B_T_Truck_01_box_F;
  class B_T_Truck_01_ammo_F;
  class USAF_C130J_Cargo;
  class USAF_C130J;
  class C_Offroad_01_F;
  class Turrets;
  class USAF_AC130U_base;
  class USAF_AC130U: USAF_AC130U_base
  {
    class Turrets: Turrets
    {
      class CopilotTurret;
      class FlightEngTurret;
      class IRTurret;
      class TVTurret;
      class FCOTurret;
      class EWOTurret;
      class NavigatorTurret;
    };
  };
  class usaf_kc135;
  class rhsusf_f22;
  class UK3CB_BAF_Apache_AH1_Generic_MTP_RM;
  class I_C_Helipilot_F;
  class I_C_Pilot_F;
  class UK3CB_ION_B_B_RIF_MED_BLK;
  class UK3CB_ION_B_B_RIF_BLK_01;
  class tfw_ilbe_blade_black;
  class UK3CB_B_I_Backpack_Radio_Chem;
